### PR TITLE
Add async support by extracting functions for updating request

### PR DESCRIPTION
**Pull request by viesti**
So one can use aws-sig4 with async functionality of clj-http.

### CODE REVIEW

**Comment by viesti** [comment]
Just a friendly bump on a fellow Clojurist from an eager patcher, any chance to get this PR reviewed @ovan ? :)

**Comment by ovan** [comment]
@viesti Sorry, missed this. Code looks good. I'll test it quickly.

**Comment by viesti** [comment]
Thanks! 

Seems that there's some sort of hiccup (not the library :)) with the CircleCI build though: https://circleci.com/gh/sharetribe/aws-sig4/32. Internet tells me stuff about TLS on Java7 (https://github.com/technomancy/leiningen/issues/2364), but would think CircleCI build container would have Java8. 

Maybe updating CircleCI config to 2.0 could help (1.0 support ends on august 31). I guess the new config should live in `.circle` directory and be something like this: https://github.com/portkey-cloud/aws-clj-sdk/blob/master/.circleci/config.yml (haven't looked into current format for a while though).

**Comment by ovan** [comment]
Yep, I noticed the build issue. Tests run locally and the code change is a clean fn extract so I pushed a new version to clojars now anyway. I'll give CircleCI 2.0 a try later to see if it fixes this.

**Pull request merged**
